/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData smile_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentiment_neutral = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile_2 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neutral = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown = IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh = IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flushed = IconData(0xf579, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown_open = IconData(0xf57a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_alt = IconData(0xf581, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin_beam = IconData(0xf582, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
